### ISSUE TITLE
建议把 google-services.json 加入 .gitignore

### ISSUE THREAD

**Issue by yanshouwang** [hotstu/QRCodeCameraX#4]
感觉 Firebase 这个 ML 比 ZXing 强多了，好东西啊

不过看到仓库里能看到你的 google-services.json 文件，这个还是排除掉的好，参考 StackOverflow 上面的讨论
https://stackoverflow.com/questions/37358340/should-i-add-the-google-services-json-from-firebase-to-my-repository

**Comment by hotstu** [comment]
多谢提醒，不过为了方便其他人运行还是保留
